# Generated by Django 4.1.7 on 2023-04-26 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publication',
            name='movie_director',
        ),
    ]
