# Generated by Django 4.1.7 on 2023-05-11 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_publication_imgur_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='favoriteslist',
            name='movie_title',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='favoriteslist',
            name='poster_img',
            field=models.URLField(default=''),
        ),
    ]
