# Generated by Django 4.1.7 on 2023-06-07 17:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0005_deslikes'),
    ]

    operations = [
        migrations.AddField(
            model_name='deslikes',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='likes',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
