# Generated by Django 4.1.7 on 2023-06-09 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0005_comment_date'),
        ('usuarios', '0005_deslikes'),
    ]

    operations = [
    ]
