# Generated by Django 4.1.7 on 2023-06-28 00:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0005_comment_date'),
        ('usuarios', '0005_deslikes'),
        ('usuarios', '0005_watchlist_movie_title_watchlist_poster_img'),
    ]

    operations = [
    ]
