# Generated by Django 4.1.7 on 2023-06-09 17:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0007_deslikes_date_likes_date_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='publication',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='usuarios.publication'),
        ),
    ]
