# Generated by Django 4.1.7 on 2023-06-17 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0008_favoriteslist_date'),
        ('usuarios', '0008_user_profile_image'),
    ]

    operations = [
    ]
